<?php
$z[0]=Array("arcurl","",32,47);
$z[0][4]=array();
$z[1]=Array("picname","",59,75);
$z[1][4]=array();
$z[2]=Array("title","",82,96);
$z[2][4]=array();
$z[3]=Array("arcurl","",162,177);
$z[3][4]=array();
$z[4]=Array("title","",179,193);
$z[4][4]=array();
$z[5]=Array("description","",210,260);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(@me,500)";
$z[6]=Array("arcurl","",285,300);
$z[6][4]=array();

?>