<?php
$z[0]=Array("channel","\n        <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\n        ",154,277);
$z[0][4]=array();
$z[0][4]['type']="top";
$z[0][4]['row']="6";
$z[1]=Array("global","",372,394);
$z[1][4]=array();
$z[1][4]['name']="cfg_add";
$z[2]=Array("global","",425,447);
$z[2][4]=array();
$z[2][4]['name']="cfg_tel";
$z[3]=Array("flink","  [field:link /]  ",479,557);
$z[3][4]=array();
$z[3][4]['titlelen']="20";
$z[3][4]['row']="20";
$z[3][4]['type']="text";
$z[4]=Array("global","",682,708);
$z[4][4]=array();
$z[4][4]['name']="cfg_powerby";

?>