<?php
$z[0]=Array("field","(@me==\"\")? @me=\" class='hover' \":@me=\"\";",228,318);
$z[0][4]=array();
$z[0][4]['name']="typeid";
$z[0][4]['runphp']="yes";
$z[1]=Array("channel","\n    <li><a href=\"[field:typeurl/]\" >[field:typename/]</a></li>\n    ",339,539);
$z[1][4]=array();
$z[1][4]['type']="top";
$z[1][4]['row']="6";
$z[1][4]['currentstyle']="<li><a href='~typelink~' class='hover'>~typename~</a></li>";
$z[2]=Array("arclist","\n    <li style=\"background:url([field:picname/]) 50% 0 no-repeat;\"></li>\n    ",606,724);
$z[2][4]=array();
$z[2][4]['typeid']="14";

?>