<div class="col-xs-6 col-sm-3 col-md-3 homeNews"> <a class="img" href="[field:arcurl/]" title="[field:title/]"> <img src="[field:picname/]"/> </a> <a class="title" href="[field:arcurl/]" title="[field:title/]"> [field:title/] </a>
              <div class="date"> [field:pubdate function="MyDate('Y-m-d',@me)"/] </div>
              <div class="content"> [field:description function="cn_substr(@me,80)"/]... </div>
              <a class="more" href="[field:arcurl/]" title="[field:title/]"> MORE + </a> </div>