<?php
$z[0]=Array("global","",278,300);
$z[0][4]=array();
$z[0][4]['name']="cfg_tel";
$z[1]=Array("flink","  [field:link /]  ",766,844);
$z[1][4]=array();
$z[1][4]['titlelen']="20";
$z[1][4]['row']="20";
$z[1][4]['type']="text";
$z[2]=Array("global","",933,959);
$z[2][4]=array();
$z[2][4]['name']="cfg_powerby";
$z[3]=Array("global","",966,990);
$z[3][4]=array();
$z[3][4]['name']="cfg_beian";
$z[4]=Array("global","",1059,1081);
$z[4][4]=array();
$z[4][4]['name']="cfg_add";
$z[5]=Array("global","",1102,1124);
$z[5][4]=array();
$z[5][4]['name']="cfg_tel";

?>