<?php
$z[0]=Array("global","",280,302);
$z[0][4]=array();
$z[0][4]['name']="cfg_tel";
$z[1]=Array("flink","  [field:link /]  ",774,852);
$z[1][4]=array();
$z[1][4]['titlelen']="20";
$z[1][4]['row']="20";
$z[1][4]['type']="text";
$z[2]=Array("global","",944,970);
$z[2][4]=array();
$z[2][4]['name']="cfg_powerby";
$z[3]=Array("global","",977,1001);
$z[3][4]=array();
$z[3][4]['name']="cfg_beian";
$z[4]=Array("global","",1071,1093);
$z[4][4]=array();
$z[4][4]['name']="cfg_add";
$z[5]=Array("global","",1114,1136);
$z[5][4]=array();
$z[5][4]['name']="cfg_tel";

?>