<?php
$z[0]=Array("global","",188,214);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",365,390);
$z[1][4]=array();
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("channelartlist","\n          <li class=\"dropdown\"><a href=\"{dede:field name='typeurl'/}\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">{dede:field name='typename'/}</a><a href=\"#\" id=\"app_menudown\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\"><span class=\"glyphicon glyphicon-menu-down btn-xs\"></span></a>\n            <ul class=\"dropdown-menu\" role=\"menu\">\n              {dede:channel type='son' noself='yes'}\n              <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\n              {/dede:channel}\n            </ul>\n          </li>\n          ",1470,2103);
$z[2][4]=array();
$z[2][4]['typeid']="top";

?>