<?php
$z[0]=Array("global","",192,218);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",372,397);
$z[1][4]=array();
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("channelartlist","\r\n          <li class=\"dropdown\"><a href=\"{dede:field name='typeurl'/}\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">{dede:field name='typename'/}</a><a href=\"#\" id=\"app_menudown\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\"><span class=\"glyphicon glyphicon-menu-down btn-xs\"></span></a>\r\n            <ul class=\"dropdown-menu\" role=\"menu\">\r\n              {dede:channel type='son' noself='yes'}\r\n              <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n              {/dede:channel}\r\n            </ul>\r\n          </li>\r\n          ",1500,2141);
$z[2][4]=array();
$z[2][4]['typeid']="top";

?>