<?php
$z[0]=Array("field","",126,184);
$z[0][4]=array();
$z[0][4]['name']="typeid";
$z[0][4]['function']="GetTopTypename(@me)";
$z[1]=Array("channel","\r\n        <li> <a href=\"[field:typeurl/]\"> [field:typename/] </a> </li>\r\n        ",252,484);
$z[1][4]=array();
$z[1][4]['type']="son";
$z[1][4]['currentstyle']="<li><a href='~typelink~' class='firstSelected selected'>~typename~</a></li>";
$z[2]=Array("global","",708,730);
$z[2][4]=array();
$z[2][4]['name']="cfg_tel";
$z[3]=Array("global","",792,814);
$z[3][4]=array();
$z[3][4]['name']="cfg_fax";
$z[4]=Array("global","",868,892);
$z[4][4]=array();
$z[4][4]['name']="cfg_email";
$z[5]=Array("global","",946,968);
$z[5][4]=array();
$z[5][4]['name']="cfg_add";

?>