<?php
$z[0]=Array("field","",124,182);
$z[0][4]=array();
$z[0][4]['name']="typeid";
$z[0][4]['function']="GetTopTypename(@me)";
$z[1]=Array("channel","\n        <li> <a href=\"[field:typeurl/]\"> [field:typename/] </a> </li>\n        ",247,475);
$z[1][4]=array();
$z[1][4]['type']="son";
$z[1][4]['currentstyle']="<li><a href='~typelink~' class='firstSelected selected'>~typename~</a></li>";
$z[2]=Array("global","",692,714);
$z[2][4]=array();
$z[2][4]['name']="cfg_tel";
$z[3]=Array("global","",775,797);
$z[3][4]=array();
$z[3][4]['name']="cfg_fax";
$z[4]=Array("global","",850,874);
$z[4][4]=array();
$z[4][4]['name']="cfg_email";
$z[5]=Array("global","",927,949);
$z[5][4]=array();
$z[5][4]['name']="cfg_add";

?>