<?php
$z[0]=Array("arcurl","",62,77);
$z[0][4]=array();
$z[1]=Array("picname","",90,106);
$z[1][4]=array();
$z[2]=Array("title","",135,149);
$z[2][4]=array();
$z[3]=Array("arcurl","",204,219);
$z[3][4]=array();
$z[4]=Array("title","",228,242);
$z[4][4]=array();
$z[5]=Array("title","",244,258);
$z[5][4]=array();
$z[6]=Array("description","",303,353);
$z[6][4]=array();
$z[6][4]['function']="cn_substr(@me,100)";

?>