<?php
$z[0]=Array("arcurl","",86,101);
$z[0][4]=array();
$z[1]=Array("picname","",142,158);
$z[1][4]=array();
$z[2]=Array("title","",185,199);
$z[2][4]=array();
$z[3]=Array("arcurl","",289,304);
$z[3][4]=array();
$z[4]=Array("title","",313,327);
$z[4][4]=array();
$z[5]=Array("title","",329,343);
$z[5][4]=array();
$z[6]=Array("description","",400,449);
$z[6][4]=array();
$z[6][4]['function']="cn_substr(@me,60)";

?>