<?php
$z[0]=Array("channel"," <a href=\"[field:typeurl/]\">[field:typename/]</a>&nbsp;&nbsp;&nbsp;&nbsp; ",43,157);
$z[0][4]=array();
$z[0][4]['type']="top";
$z[1]=Array("global","",190,216);
$z[1][4]=array();
$z[1][4]['name']="cfg_powerby";
$z[2]=Array("global","",229,253);
$z[2][4]=array();
$z[2][4]['name']="cfg_beian";
$z[3]=Array("global","",381,403);
$z[3][4]=array();
$z[3][4]['name']="cfg_tel";

?>