<?php
$z[0]=Array("field","",108,166);
$z[0][4]=array();
$z[0][4]['name']="typeid";
$z[0][4]['function']="GetTopTypename(@me)";
$z[1]=Array("channel","\n      <li> <a href=\"[field:typeurl/]\">[field:typename/]</a></li>\n      ",222,424);
$z[1][4]=array();
$z[1][4]['type']="son";
$z[1][4]['currentstyle']="<li><a href='~typelink~' class='biglink'>~typename~</a></li>";
$z[2]=Array("type","\n    <h2 class=\"title_h2\">[field:typename/]</h2>\n    ",470,558);
$z[2][4]=array();
$z[2][4]['typeid']="10";
$z[3]=Array("arclist","\n      <li><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></li>\n      ",593,764);
$z[3][4]=array();
$z[3][4]['typeid']="10";
$z[3][4]['row']="5";
$z[3][4]['titlelen']="50";
$z[3][4]['orderby']="pubdate";
$z[4]=Array("type","\n    <h2 class=\"title_h2\">[field:typename/]</h2>\n    ",814,902);
$z[4][4]=array();
$z[4][4]['typeid']="15";
$z[5]=Array("global","",941,962);
$z[5][4]=array();
$z[5][4]['name']="cfg_qq";
$z[6]=Array("global","",983,1005);
$z[6][4]=array();
$z[6][4]['name']="cfg_tel";
$z[7]=Array("global","",1026,1048);
$z[7][4]=array();
$z[7][4]['name']="cfg_fax";
$z[8]=Array("global","",1069,1093);
$z[8][4]=array();
$z[8][4]['name']="cfg_email";
$z[9]=Array("global","",1115,1137);
$z[9][4]=array();
$z[9][4]['name']="cfg_add";

?>