<?php
$z[0]=Array("field","",30,58);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",83,109);
$z[1][4]=array();
$z[1][4]['name']="currentstyle";
$z[2]=Array("field","",134,163);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("channel","\n              <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\n              ",408,548);
$z[3][4]=array();
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";

?>