<?php
$z[0]=Array("global","",153,174);
$z[0][4]=array();
$z[0][4]['name']="cfg_gg";
$z[1]=Array("global","",255,277);
$z[1][4]=array();
$z[1][4]['name']="cfg_tel";
$z[2]=Array("global","",319,343);
$z[2][4]=array();
$z[2][4]['name']="cfg_email";
$z[3]=Array("global","",945,971);
$z[3][4]=array();
$z[3][4]['name']="cfg_webname";
$z[4]=Array("field","(@me==\"\")? @me=\" class='selecteded' \":@me=\"\";",1104,1199);
$z[4][4]=array();
$z[4][4]['name']="typeid";
$z[4][4]['runphp']="yes";
$z[5]=Array("channelartlist","\n          <li class=\"dropdown\"><a href=\"{dede:field name='typeurl'/}\" class=\"dropdown-toggle {dede:field.currentstyle/}\" data-toggle=\"dropdown\">{dede:field name='typename'/}</a><a href=\"#\" id=\"app_menudown\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\"><span class=\"glyphicon glyphicon-menu-down btn-xs\"></span></a>\n            <ul class=\"dropdown-menu\" role=\"menu\">\n              {dede:channel type='son' noself='yes'}\n              <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\n              {/dede:channel}\n            </ul>\n          </li>\n          ",1232,1918);
$z[5][4]=array();
$z[5][4]['typeid']="top";
$z[5][4]['currentstyle']="selecteded";

?>