<?php
$z[0]=Array("field","",130,188);
$z[0][4]=array();
$z[0][4]['name']="typeid";
$z[0][4]['function']="GetTopTypename(@me)";
$z[1]=Array("channel","\n        <li> <a href=\"[field:typeurl/]\"> [field:typename/] </a> </li>\n        ",306,534);
$z[1][4]=array();
$z[1][4]['type']="son";
$z[1][4]['currentstyle']="<li><a href='~typelink~' class='firstSelected selected'>~typename~</a></li>";
$z[2]=Array("type","\n    <div class=\"titleBar\">\n      <h5> [field:typename/] </h5>\n      <span> NEWS CENTER </span> </div>\n    ",591,733);
$z[2][4]=array();
$z[2][4]['typeid']="10";
$z[3]=Array("arclist","\n      <li> <a href=\"[field:arcurl/]\" title=\"[field:title/]\"> [field:title/] </a> </li>\n      ",766,941);
$z[3][4]=array();
$z[3][4]['typeid']="10";
$z[3][4]['row']="5";
$z[3][4]['titlelen']="50";
$z[3][4]['orderby']="pubdate";
$z[4]=Array("type","\n    <div class=\"titleBar\">\n      <h5> [field:typename/] </h5>\n      <span> CONTACT US </span> </div>\n    ",988,1129);
$z[4][4]=array();
$z[4][4]['typeid']="15";
$z[5]=Array("global","",1207,1229);
$z[5][4]=array();
$z[5][4]['name']="cfg_tel";
$z[6]=Array("global","",1288,1310);
$z[6][4]=array();
$z[6][4]['name']="cfg_fax";
$z[7]=Array("global","",1361,1385);
$z[7][4]=array();
$z[7][4]['name']="cfg_email";
$z[8]=Array("global","",1436,1458);
$z[8][4]=array();
$z[8][4]['name']="cfg_add";

?>